[tool.commitizen]
name = "cz_conventional_commits"
version = "0.1.0"
version_scheme = "semver"
tag_format = "v$version"
changelog_file = "CHANGELOG.md"
changelog_incremental = true
update_changelog_on_bump = true
major_version_zero = true
